document.write('			<div id="KeyVisual">');
document.write('				<ul id="Key1menu">');
document.write('					<li><div id="K01" ><img src="../../img/keyLabels/1.png" width="221" height="21" /></div>');
document.write('						<a href="#" id="key_decel" class="menu01" onmouseover="showPopup(\'K01\')" onmouseout="hidePopup(\'K01\')"><span>K01</span></a>');
document.write('					</li>');
document.write('					<li><div id="K02"><img src="../../img/keyLabels/2.png" width="256" height="21" /></div>');
document.write('						<a href="#" id="key_mode" class="menu02" onmouseover="showPopup(\'K02\')" onmouseout="hidePopup(\'K02\')"><span>K02</span></a>');
document.write('					</li>');
document.write('					<li><div id="K03"><img src="../../img/keyLabels/3.png" width="251" height="21" /></div>');
document.write('						<a href="#" id="key_speed" class="menu03" onmouseover="showPopup(\'K03\')" onmouseout="hidePopup(\'K03\')"><span>K03</span></a>');
document.write('					</li>');
document.write('				</ul>');
document.write('				<ul id="Key2menu">');
document.write('					<li><div id="K04"><img src="../../img/keyLabels/4.png" width="184" height="21" /></div>');
document.write('						<a href="#" id="key_04" class="menu04" onmouseover="showPopup(\'K04\')" onmouseout="hidePopup(\'K04\')"><span>K04</span></a></li>');
document.write('					<li><div id="K05"><img src="../../img/keyLabels/5.png" width="118" height="21" /></div>');
document.write('						<a href="#" id="key_05" class="menu05" onmouseover="showPopup(\'K05\')" onmouseout="hidePopup(\'K05\')"><span>K05</span></a></li>');
document.write('					<li><div id="K06"><img src="../../img/keyLabels/6.png" width="196" height="21" /></div>');
document.write('						<a href="#" id="key_06" class="menu06" onmouseover="showPopup(\'K06\')" onmouseout="hidePopup(\'K06\')"><span>K06</span></a></li>');
document.write('				</ul>');
document.write('				<ul id="Key3menu">');
document.write('					<li><div id="K07"><img src="../../img/keyLabels/7.png" width="101" height="21" /></div>');
document.write('						<a href="#" id="key_07" class="menu07" onmouseover="showPopup(\'K07\')" onmouseout="hidePopup(\'K07\')"><span>K07</span></a></li>');
document.write('					<li><div id="K08"><img src="../../img/keyLabels/8.png" width="243" height="21" /></div>');
document.write('						<a href="#" id="key_08" class="menu08" onmouseover="showPopup(\'K08\')" onmouseout="hidePopup(\'K08\')"><span>K08</span></a></li>');
document.write('					<li><div id="K09"><img src="../../img/keyLabels/9.png" width="116" height="21" /></div>');
document.write('						<a href="#" id="key_09" class="menu09" onmouseover="showPopup(\'K09\')" onmouseout="hidePopup(\'K09\')"><span>K09</span></a></li>');
document.write('					<li><div id="K10"><img src="../../img/keyLabels/7.png" width="101" height="21" /></div>');
document.write('						<a href="#" id="key_10" class="menu10" onmouseover="showPopup(\'K10\')" onmouseout="hidePopup(\'K10\')"><span>K10</span></a></li>');
document.write('					<li><div id="K11"><img src="../../img/keyLabels/8.png" width="243" height="21" /></div>');
document.write('						<a href="#" id="key_00" class="menu11" onmouseover="showPopup(\'K11\')" onmouseout="hidePopup(\'K11\')"><span>K11</span></a></li>');
document.write('					<li><div id="K12"><img src="../../img/keyLabels/10.png" width="195" height="21" /></div>');
document.write('						<a href="#" id="key_12" class="menu12" onmouseover="showPopup(\'K12\')" onmouseout="hidePopup(\'K12\')"><span>K12</span></a></li>');
document.write('					<li><div id="K13"><img src="../../img/keyLabels/11.png" width="248" height="21" /></div>');
document.write('						<a href="#" id="key_13" class="menu13" onmouseover="showPopup(\'K13\')" onmouseout="hidePopup(\'K13\')"><span>K13</span></a></li>');
document.write('					<li><div id="K14"><img src="../../img/keyLabels/12.png" width="184" height="21" /></div>');
document.write('						<a href="#" id="key_14" class="menu14" onmouseover="showPopup(\'K14\')" onmouseout="hidePopup(\'K14\')"><span>K14</span></a></li>');
document.write('					<li><div id="K15"><img src="../../img/keyLabels/13.png" width="100" height="21" /></div>');
document.write('						<a href="#" id="key_15" class="menu15" onmouseover="showPopup(\'K15\')" onmouseout="hidePopup(\'K15\')"><span>K15</span></a></li>');
document.write('				</ul>');
document.write('			</div>');